# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_nr', models.IntegerField(help_text='Just a dummy number')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
